### ISSUE TITLE
Possible panic due to processing time out of sync in multi level deployment

### ISSUE THREAD

**Issue by lahsivjar** [elastic/apm-aggregation#119]
## Description

Each instance of aggregator initializes its own processing time using `time.Now` ([ref](https://github.com/elastic/apm-aggregation/blob/e3fee96967e98e35c84a1d991039d9b11b6de614/aggregators/aggregator.go#L113)). As a result, in multi level deployments, it is possible that processing time of some instances is in the future w.r.t. others. For example: with a 2 level deployment, L1 is running with processing time = `t0` while L2 is running with processing time as `t0-1m`. In such cases, we will have a panic for metric calculation where we assume that all events accepted in current processing time should be harvested when the current processing time ends. Example of possible panic:

```
panic: assignment to entry in nil map

goroutine 137734 [running]:
github.com/elastic/apm-aggregation/aggregators.(*Aggregator).harvestForInterval(0xc0001c6dc0, {0x1876bd8, 0xc00220fc50}, 0xc001e16b80?, {0x0?, 0x46881a?, 0x232cc40?}, {0x0, 0xedc9c9678, 0x232cc40}, ...)
	github.com/elastic/apm-aggregation@v0.0.0-20230920060649-e3fee96967e9/aggregators/aggregator.go:541 +0xfa5
github.com/elastic/apm-aggregation/aggregators.(*Aggregator).harvest(0xc0001c6dc0, {0x1876bd8, 0xc00220fc50}, {0x232cc40?, 0x0?, 0x232cc40?}, 0x0?)
	github.com/elastic/apm-aggregation@v0.0.0-20230920060649-e3fee96967e9/aggregators/aggregator.go:432 +0x298
github.com/elastic/apm-aggregation/aggregators.(*Aggregator).Close(0xc0001c6dc0, {0x1876b30?, 0xc001f76ff0?})
	github.com/elastic/apm-aggregation@v0.0.0-20230920060649-e3fee96967e9/aggregators/aggregator.go:307 +0x59d
github.com/elastic/apm-aggregation-service/pipelines.(*Pipeline).Stop(0xc000412750, {0x1876b30, 0xc001f76ff0})
	github.com/elastic/apm-aggregation-service/pipelines/pipeline.go:173 +0x7d
main.serve.func1.1()
	github.com/elastic/apm-aggregation-service/main.go:74 +0x25
golang.org/x/sync/errgroup.(*Group).Go.func1()
	golang.org/x/sync@v0.3.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	golang.org/x/sync@v0.3.0/errgroup/errgroup.go:72 +0xa5
```

## Solution

One possible solution to fix this is to include processing time as a key in the `cachedEventsMap` ([ref](https://github.com/elastic/apm-aggregation/blob/e3fee96967e98e35c84a1d991039d9b11b6de614/aggregators/cachedeventsmap.go#L61)).

**Comment by simitt** [comment]
@kruskall please consult with @lahsivjar on the best path forward before implementation

**Comment by simitt** [comment]
When removing L2 aggregator (https://github.com/elastic/apm-aggregation-service/issues/417), this shouldn't be necessary anymore.

**Comment by marclop** [comment]
@lahsivjar after #417 is closed, this should be automatically resolved, right?
